# Generated by Django 5.1.4 on 2024-12-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resaleflat",
            unique_together={
                ("month", "town", "flat_type", "block", "street_name", "resale_price")
            },
        ),
    ]
